### ISSUE TITLE
pnpm run start  启动问题

### ISSUE THREAD

**Issue by nalafei** [tansen87/pywebview-vue3-template#1]
执行 pnpm run start  命令后，打开的窗口提示脚本错误 ，是哪里没有配置好吗？

**Comment by tansen87** [comment]
@nalafei 可以麻烦您提供一下详细的报错信息吗

**Comment by nalafei** [comment]
![微信图片_20241206065930](https://github.com/user-attachments/assets/3bdcd8a1-404b-44c9-bc72-b593bb6eee6b)

**Comment by nalafei** [comment]
这是哪里的问题呀？老师

**Comment by tansen87** [comment]
@nalafei clone最新的代码再运行看看，或者F12看看console的输出
